

equation: "poisson_1d-x2_add_sinx" # sin(500x)-2*(x-0.5)^2
num_u_trick: 1
Q: 30
lr: 0.01
llk_weight: 200
freq_scale: 100
logdet: True
num_fold: 1     # as it's a deterministic algorithm, we can run it for only one fold
tol: -1 # set as positive value to enable the early stopping
N_col: 400
scale: '1'
other_paras: '-x-1'
nepoch: 1000000
change_point: 0.01 # only used for the extra_GP 


