

equation: "poisson_1d-mix_sin" #  sin(x) + 0.1*sin(20x) + 0.05*cos(100x)
num_u_trick: 1
Q: 30
lr: 0.01
llk_weight: 200
freq_scale: 30
logdet: True
num_fold: 1     # as it's a deterministic algorithm, we can run it for only one fold
tol: -1 # set as positive value to enable the early stopping
N_col: 900
scale: '1'
other_paras: '-x-1'
nepoch: 100000
change_point: 0.5 # only used for the extra_GP 


