

equation: "poisson_1d-single_sin" # sin(100 * x)
num_u_trick: 1
Q: 30
lr: 0.01
llk_weight: 200
freq_scale: 20
logdet: True
num_fold: 1     # as it's a deterministic algorithm, we can run it for only one fold
tol: -1 # set as positive value to enable the early stopping
N_col: 400
scale: '2pi'
other_paras: '-x-2pi'
nepoch: 100000

