

equation: "advection-sin" # sin(x-beta*y)
num_u_trick: 1
Q: 30
lr: 0.01
llk_weight: 500
freq_scale: 40
logdet: True
num_fold: 1     # as it's a deterministic algorithm, we can run it for only one fold
tol: -1 # set as positive value to enable the early stopping
N_col: 200
scale: '1'
other_paras: '-x-1'
nepoch: 200000
beta: 200

# sub-optimal parameters
# N_col: 200
# nepoch: 1000000