

equation: "allencahn_2d-mix-sincos" #  (jnp.sin(x) + 0.1 * jnp.sin(20 * x) + jnp.cos(100 * x)) * (jnp.sin(y) + 0.1 * jnp.sin(20 * y) + jnp.cos(100 * y))
num_u_trick: 1
Q: 30
lr: 0.01
llk_weight: 200
freq_scale: 30
logdet: True
num_fold: 1     # as it's a deterministic algorithm, we can run it for only one fold
tol: -1 # set as positive value to enable the early stopping
N_col: 200
scale: '1'
other_paras: '-x-1'
nepoch: 3000000
